import MatchModel from "./Match.model";
import PerformanceModel from "./Performance.model";
import CompetitionModel from "./Competition.model";
import StatsModel from "./Stats.model";
import OpponentStatsModel from "./OpponentStats.model";
import VenueStatsModel from "./VenueStats.model";
import SeasonStatsModel from "./SeasonStats.model";
import MilestoneModel from "./Milestone.model";
import TimelineModel from "./Timeline.model";
import PlayerModel from "./Player.model";

export const Match = MatchModel;
export const Performance = PerformanceModel;
export const Competition = CompetitionModel;
export const Stats = StatsModel;
export const OpponentStats = OpponentStatsModel;
export const VenueStats = VenueStatsModel;
export const SeasonStats = SeasonStatsModel;
export const Milestone = MilestoneModel;
export const Timeline = TimelineModel;
export const Player = PlayerModel;